### PR TITLE
[TASK] Migrate to Doctrine DBAL and remove TYPO3_DB

### PR DESCRIPTION
**Pull request by bmack**
This change also removes the dependency to
legacy extension as this is not used anymore.

### CODE REVIEW

**Comment by bmack** [comment]
This is a first draft, will need to test all the use-cases. But just so you know it's there and we don't need to do duplicate work!

**Comment by 7elix** [comment]
Shall I solve the CGL merge conflicts or do we wait until feature is ready?

**Comment by bmack** [comment]
we can get it into master if that's ok with you. I'll have my test installation running with `dev-master` anyway. From there on I can continue on fixing other bugs, if you'd like. then I don't have to have so many multiple branches.

**Comment by bmack** [comment]
Works on production since today.

**Comment by 7elix** [comment]
<3

**Comment by SvenJuergens** [comment]
👍 sounds great

**Pull request merged**
