### PR TITLE
version 2.4.1e - initial 10.4 compat changes. needs more work but bas…

### PR DESCRIPTION
**Pull request by 7elix**
…ically works

### CODE REVIEW

**Comment by 7elix** [comment]
#54

**Comment by h3nn3s** [comment]
Tested this PR in our Upgrade Project to 10LTS. No errors so far :+1:

**Comment by 7elix** [comment]
You still have the "Draft" flag on your branch.

In the meantime several changes were merged: phpstan, rector and feature-10 branch. Would you like to update your branch? This certainly helps. Thanks.

**Comment by w010** [comment]
> You still have the "Draft" flag on your branch.

I can't find anywhere, where to change that.
 
> In the meantime several changes were merged: phpstan, rector and feature-10 branch. Would you like to update your branch?

Ok I'll review the situation later this week.

**Pull request closed without merging**
